from .user import User
from .token_blocklist import TokenBlocklist
from .department import Department
from .doctor import Doctor
from .patient import Patient
from .appointment import Appointment
from .medical_record import MedicalRecord
from .nurse import Nurse
from .applications import Application
from .patient_vitals import PatientVital
